SAMPLES: config/samples.tsv

OUTPUT:
    REF: 
        - hg38
    RUN:
        QC: False
        PEAKS: True
        BWS: True
        CHIPATLASBED: False
        CHIPATLASBIGWIG: False
    BW_NORMALIZATIONS: # , BPM, RPGC, None
        - RPKM
        - CPM
    BAMPROCESS_PARAMS: -q 30
    MACS_THRESHOLD: 
        - 0.01
    CHIPATLASBED_THRESHOLD: '05'

UPDATE_CHIPATLAS: False  # Whether to update CHIP-Atlas experimentList.tab
