SAMPLES: config/samples.tsv

OUTPUT:
    REF: hg38
    RUN:
        QC: False
        PEAKS: True
        BWS: True
        CHIPATLASBED: False
        CHIPATLASBIGWIG: False
    BW_NORMALIZATIONS: # , BPM, RPGC, None
        - RPKM
        - CPM
    BAMPROCESS_PARAMS: -q 30
    MACS_THRESHOLD: 0.01
    IDR_THRESHOLD: 0.05
    CHIPATLASBED_THRESHOLD: '05'

CHIPATLAS: 
    UPDATE: False  # Whether to update CHIP-Atlas experimentList.tab

CUT_ADAPTERS:
    ADAPTER_FWD: AGATCGGAAGAGCACACGTCTGAACTCCAGTCA  # Illumina adapter R1
    ADAPTER_REV: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT  # Illumina adapter R2
    MIN_LENGTH: 20
